package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"football-subgraph/football_data"
	"football-subgraph/graph/model"
)

// UpcomingMatches is the resolver for the upcomingMatches field.
func (r *queryResolver) UpcomingMatches(ctx context.Context) ([]*model.Match, error) {
	return football_data.GetMatches()
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
